name: Unittest Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  unittest:
    name: Run unittests
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v7"
        - name: Set up python
          uses: "actions/setup-python@v7"
          with:
            python-version: "3.14"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt -r requirements_test.txt
        - name: Show homeasssistant version
          HA_VERSION=$(python -c "import homeassistant; print(homeassistant.__version__)")
          PYTEST_HA_VERSION=$(python -c "import pytest-homeassistant-custom-component; print(pytest-homeassistant-custom-component.__version__)")
          run: echo "::notice title=HA version used::ha=$HA_VERSION,  pytest ha=$PYTEST_HA_VERSION"
        - name: Test with pytest
          run: pytest
