name: Unittest Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  unittest:
    name: Run unittests
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v7"
        - name: Set up python
          uses: "actions/setup-python@v7"
          with:
            python-version: "3.14"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt -r requirements_test.txt
        - name: Show homeasssistant version
          run: |
             HA_VERSION=$(pip show homeassistant | grep Version)
             PYTEST_HA_VERSION=$(pip show pytest-homeassistant-custom-component | grep Version)
             echo "::notice title=HA version used::ha $HA_VERSION,  pytest $PYTEST_HA_VERSION"
        #- name: Test with pytest
        #  run: pytest
