name: HACS and hassfest Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  hacs:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: integration
  hassfest:
    name: Hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
  unittest:
    name: Run unittests
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v7"
        - name: Set up python
          uses: "actions/setup-python@v7"
          with:
            python-version: "3.14"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt -r requirements_test.txt
        - name: Test with pytest
          run: pytest
